language: php

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

sudo: false

script:
  - ./phpunit

notifications:
  email: false

    on_success: false
    on_failure: always
